apiVersion: v1
kind: ConfigMap
metadata:
  name: zota-server-config
  namespace: zota
data:
  SPRING_PROFILES_ACTIVE: "postgresql"
  HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_TARGETTOKEN_ENABLED: "true"
  HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_GATEWAYTOKEN_ENABLED: "true"
  HAWKBIT_SERVER_REPOSITORY_PUBLISH_TARGET_POLL_EVENT: "false"
  JAVA_OPTS: "-Xms512m -Xmx1024m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=128m -XX:ReservedCodeCacheSize=128m"
  CORS_ORIGINS: "http://zota-web.intra.zeron.ai,https://zota-repo-web.intra.zeron.ai,http://localhost:3000,http://localhost:5173"
