apiVersion: v1
kind: ConfigMap
metadata:
  name: zota-server-config
  namespace: zota
data:
  SPRING_PROFILES_ACTIVE: "postgresql"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.zota.svc:5432/zota_server"
  SPRING_RABBITMQ_HOST: "rabbitmq.zota.svc"
  SPRING_RABBITMQ_PORT: "5672"
  HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_TARGETTOKEN_ENABLED: "true"
  HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_GATEWAYTOKEN_ENABLED: "true"
  HAWKBIT_SERVER_REPOSITORY_PUBLISH_TARGET_POLL_EVENT: "false"
  JAVA_OPTS: "-Xms512m -Xmx1024m"
