apiVersion: v1
kind: Service
metadata:
  name: zota-server
  namespace: zota
  labels:
    app: zota-server
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: zota-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zota-server-artifacts
  namespace: zota
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
